name: Waka Readme

on:
  schedule:
    # Runs at 12am BRT
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "false"
          SHOW_TIMEZONE: "false"
          SHOW_EDITORS: "false"
          SHOW_LANGUAGE_PER_REPO: "false"
          SYMBOL_VERSION: "3"
          LOCALE: "pt"
          SHOW_LOC_CHART: "false"
          
